language: node_js
node_js:
  - 6.9.5
cache: yarn
before_install:
  - yarn global add @angular/cli@latest
script:
  - npm run build
before_deploy:
  - cp server.js dist/server.js
  - cd dist 
  - yarn init --yes
  - yarn add express 
deploy:
  provider: heroku
  api_key:
    secure: c951e33f-7b3d-4228-9d58-4bfb880d14cd
  app: tajawal
  branch: master
