language: node_js
node_js:
  - 6.9.5
cache: yarn
before_install:
  - yarn global add @angular/cli@latest
install: yarn
script:
  - npm run test
  - npm run build
after_script:
  - chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  api_key:
    secure: c951e33f-7b3d-4228-9d58-4bfb880d14cd
  app: tajawal
  branch: master
