language: node_js
node_js:
  - "iojs"
  - "7"
before_install:
  - sudo apt-get install build-essential libssl-dev libffi-dev python-dev
  - npm install -g node-gyp socket.io
  - sudo apt-get update
  - sudo apt-get install python2.7
  - sudo apt-get install python3.6