language: node_js
node_js:
  - 6.9.5
before_install:
  - npm i -g @angular/cli@latest
install: npm i
script:
  - npm run test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: c951e33f-7b3d-4228-9d58-4bfb880d14cd
  app: tajawal
  branch: master
